server:
  port: ${SERVER_PORT:8080}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: lang/messages
    encoding: UTF-8
security:
  secret:
    jwtExpirationMs: 300000
    refreshTokenDurationMs: 300
    key: VGhpcyBpcyBteSBzZWNyZXQga2V5IGJhc2U2NCBiYXNlNjQgYmFzZTY0IGJhc2U2NA==

#logging:
#  level:
#    org.springframework: INFO
    #    org.hibernate: DEBUG
#    {main package path}: INFO

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration