spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:cinema_app}
    username: ${DB_CONNECTION_USERNAME:postgres}
    password: ${DB_CONNECTION_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CLASSPATH:classpath:db/db.changelog-${ACTIVE_PROFILE:master}.yaml}
    url: jdbc:postgresql://localhost:5432/${DB_NAME:cinema_app}
    user: postgres
    password: mysecretpassword
    default-schema: cinema_app