spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:cinema_app}?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_CONNECTION_USERNAME:postgres}
    password: ${DB_CONNECTION_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}
    change-log: ${LIQUIBASE_CLASSPATH:classpath:db/db.changelog-${ACTIVE_PROFILE:master}.yaml}
    url: jdbc:postgresql://localhost:5432/${DB_NAME:cinema_app}
    user: postgres
    password: mysecretpassword
    default-schema: cinema_app